"""initial tables

Revision ID: 52d7904348c5
Revises: 
Create Date: 2026-03-18 14:53:26.048884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52d7904348c5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('areas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('activa', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_areas_id'), 'areas', ['id'], unique=False)
    op.create_table('capacitaciones',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre_capacitador', sa.String(length=100), nullable=False),
    sa.Column('area_capacitadora', sa.String(length=150), nullable=False),
    sa.Column('fecha_carga', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('tema', sa.String(length=255), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('archivo_url', sa.String(length=500), nullable=True),
    sa.Column('archivo_nombre', sa.String(length=255), nullable=True),
    sa.Column('archivo_tipo', sa.String(length=50), nullable=True),
    sa.Column('archivo_tamanio', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('capacitacion_areas',
    sa.Column('capacitacion_id', sa.UUID(), nullable=False),
    sa.Column('area_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], ),
    sa.ForeignKeyConstraint(['capacitacion_id'], ['capacitaciones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('capacitacion_id', 'area_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('capacitacion_areas')
    op.drop_table('capacitaciones')
    op.drop_index(op.f('ix_areas_id'), table_name='areas')
    op.drop_table('areas')
    # ### end Alembic commands ###
