"""area_capacitadora_to_fk

Revision ID: 9df5636317b8
Revises: 52d7904348c5
Create Date: 2026-03-18 15:31:07.966919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9df5636317b8'
down_revision: Union[str, Sequence[str], None] = '52d7904348c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('capacitaciones', sa.Column('area_capacitadora_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'capacitaciones', 'areas', ['area_capacitadora_id'], ['id'])
    op.drop_column('capacitaciones', 'area_capacitadora')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('capacitaciones', sa.Column('area_capacitadora', sa.VARCHAR(length=150), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'capacitaciones', type_='foreignkey')
    op.drop_column('capacitaciones', 'area_capacitadora_id')
    # ### end Alembic commands ###
